{{- if .Values.kagent.provisioningToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kagent.fullname" . }}-secret
  labels:
    {{- include "kagent.labels" . | nindent 4 }}
type: Opaque
stringData:
  K_REGISTER_PROVISIONING_TOKEN: {{ .Values.kagent.provisioningToken | quote }}
---
{{- end }}
