apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kagent.fullname" . }}-provisioning-token
  labels:
    {{- include "kagent.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.kagent.provisioningToken | b64enc | quote }}
